ALTER TABLE IF EXISTS tbl_products
ADD IF NOT EXISTS quantity INTEGER NOT NULL CONSTRAINT default_quantity DEFAULT 0;
ALTER TABLE IF EXISTS tbl_products ALTER quantity DROP DEFAULT;
ALTER TABLE IF EXISTS tbl_products DROP IF EXISTS quantity;