CREATE TABLE IF NOT EXISTS tbl_bank_account
(
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(150) NOT NULL,
	last_name VARCHAR(150) NOT NULL,
	country VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	address VARCHAR(250) NOT NULL,
	phone_number VARCHAR(20) UNIQUE NOT NULL,
	card_number VARCHAR(16) UNIQUE NOT NULL,
	balance MONEY DEFAULT(0)
);