CREATE TABLE IF NOT EXISTS tbl_phonebook (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	second_name VARCHAR(100),
	phone INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_scoolshedule (
	id SERIAL PRIMARY KEY,
	lesson VARCHAR(100) NOT NULL,
	lesson_date DATE NOT NULL DEFAULT CURRENT_DATE,
	start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	teacher VARCHAR(100) NOT NULL,
	groupe VARCHAR(5) NOT NULL,
	room SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_logtable (
	id SERIAL PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	start_date DATE NOT NULL,
	start_time TIMESTAMP NOT NULL,
	end_date DATE NOT NULL,
	end_time TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_bankaccounts (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	second_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100),
	register_date DATE NOT NULL DEFAULT CURRENT_DATE,
	birth_date DATE NOT NULL DEFAULT CURRENT_DATE,
	inn SERIAL NOT NULL,
	address VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_transactions (
	id SERIAL PRIMARY KEY,
	start_date DATE NOT NULL,
	start_time TIMESTAMP NOT NULL,
	sender VARCHAR(200) NOT NULL,
	receiver VARCHAR(200) NOT NULL,
	completed BOOL,
	amount MONEY NOT NULL,
	discription VARCHAR (100)
);